name: reusables
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  intl: ^0.18.1
