name: reusables
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  intl: ^0.18.0
